name: Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore /p:TargetFramework=net8.0

      - name: Build
        run: dotnet build --configuration Release -f net8.0 --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release -f net8.0 --no-build --verbosity normal
